services:
    _defaults:
        public: true
        autowire: true
    paybox.request_handler:
        class: 'Antilop\Bundle\PayboxBundle\Paybox\System\Base\Request'
        arguments: ['%paybox.parameters%', '%paybox.servers%', '@form.factory']

    paybox.request_cancellation_handler:
        class: 'Antilop\Bundle\PayboxBundle\Paybox\System\Cancellation\Request'
        arguments: ['%paybox.parameters%', '%paybox.servers%', '@paybox.transport']

    paybox.response_handler:
        class: 'Antilop\Bundle\PayboxBundle\Paybox\System\Base\Response'
        arguments: ['@request_stack', '@logger', '@event_dispatcher', '%paybox.parameters%']
        tags:
            - { name: monolog.logger, channel: payment }

    paybox.controller.submit:
        class: 'Antilop\Bundle\PayboxBundle\Controller\SubmitController'

    paybox.controller.ipn:
        class: 'Antilop\Bundle\PayboxBundle\Controller\IpnController'

    paybox.transport:
        class: 'Antilop\Bundle\PayboxBundle\Transport\CurlTransport'

