parameters:
    paybox.request_handler.class:              'Antilop\Bundle\PayboxBundle\Paybox\System\Base\Request'
    paybox.request_cancellation_handler.class: 'Antilop\Bundle\PayboxBundle\Paybox\System\Cancellation\Request'
    paybox.response_handler.class:             'Antilop\Bundle\PayboxBundle\Paybox\System\Base\Response'

services:
    _defaults:
        public: true
        autowire: true
    paybox.request_handler:
        class: 'Antilop\Bundle\PayboxBundle\Paybox\System\Base\Request'
        arguments: ['%paybox.parameters%', '%paybox.servers%', '@form.factory']

    paybox.request_cancellation_handler:
        class: 'Antilop\Bundle\PayboxBundle\Paybox\System\Cancellation\Request'
        arguments: ['%paybox.parameters%', '%paybox.servers%', '@paybox.transport']

    paybox.response_handler:
        class: 'Antilop\Bundle\PayboxBundle\Paybox\System\Base\Response'
        arguments: ['@request_stack', '@logger', '@event_dispatcher', '%paybox.parameters%']
        tags:
            - { name: monolog.logger, channel: payment }

    paybox.direc_plus.request_handler:
        class: '%paybox.direc_plus.request_handler%'
        arguments: ['%paybox.parameters%', '%paybox.servers%', '@logger', '@event_dispatcher', '@paybox.transport']
        tags:
            - { name: monolog.logger, channel: payment }

    paybox.transport:
        class: '%paybox.transport.class%'
